"""Nivell 1 de R-Type ASCII: PRIMER CONTACTE.

Cada nivell viu en un fitxer propi numerat (nivell_1.py, nivell_2.py...) al
costat de main.py; el joc els carrega tots en ordre numeric en arrencar.

Aquest nivell va ser CONVERTIT AUTOMATICAMENT des de l'antic format
d'elevacions a la v0.6.0: conserva exactament els mateixos perfils de roca,
colors (vora i cos de cada segment) i temps d'entrada de cada columna. El
terreny es DIBUIXAT (format 'art'; la referencia completa del format es el
docstring de nivell_4.py): FILES de dibuix, una columna del dibuix per cada
columna del nivell; tot caracter de PALETA es solid i l'espai es lliure. El
fons (estels, un planeta llunya i muntanyes fosques) es purament estetic i
avanca mes lent que el primer pla.

Dura 1800 ticks (uns 144 segons a 12.5 FPS) en cinc fases de dificultat
creixent:

  1. BENVINGUDA      bumps petits per aprendre la mecanica de les parets.
  2. PRIMERES ROQUES crestes i estalactites alternades, primeres parelles.
  3. EL CANAL EN S   corredor que baixa i puja + porta vermella amb cristall.
  4. LES PINCES      dalt i baix tanquen alhora; murs amb una sola sortida.
  5. ESPRINT FINAL   cadena ritmica de bumps, tunell i gran porta final.

Els enemics no xoquen amb la roca; cap spawn cau sobre una columna amb roca.
"""

FILES = 20                    # ART_CANON_H: files de tot dibuix

PALETA = {
    "#": ("#", "91"),
    "%": ("%", "90"),
    "@": ("@", "95"),
    "E": ("%", "32"),
    "Q": ("#", "97"),
    "R": ("#", "95"),
    "W": ("#", "96"),
    "Y": ("#", "93"),
    "e": ("#", "92"),
    "q": ("%", "94"),
    "r": ("#", "37"),
    "t": ("%", "95"),
    "w": ("%", "33"),
    "y": ("%", "35"),
}

PALETA_FONS = {
    ".": (".", "90"),
    "*": ("*", "37"),
    "O": ("O", "37"),
    "o": ("o", "33"),
    "^": ("^", "34"),
}


def junta(*paneles):
    """Enganxa panells de 20 files horitzontalment en un sol dibuix."""
    return tuple("".join(fila) for fila in zip(*paneles))


def cel(n):
    """Panel de cel obert: n columnes del tot lliures."""
    return (" " * n,) * FILES


# Roca del tick 120 al 124 (5 columnes)
PANELL_02 = (
    "eEEEe",
    " eEe ",
    "  e  ",
    "     ",
    "     ",
    "     ",
    "     ",
    "     ",
    "     ",
    "     ",
    "     ",
    "     ",
    "     ",
    "     ",
    "     ",
    "     ",
    "     ",
    "     ",
    "     ",
    "     ",
)

# Roca del tick 200 al 204 (5 columnes)
PANELL_04 = (
    "     ",
    "     ",
    "     ",
    "     ",
    "     ",
    "     ",
    "     ",
    "     ",
    "     ",
    "     ",
    "     ",
    "     ",
    "     ",
    "     ",
    "     ",
    "     ",
    "     ",
    "  r  ",
    " r%r ",
    "r%%%r",
)

# Roca del tick 280 al 286 (7 columnes)
PANELL_06 = (
    "eEEEEEe",
    " eEEEe ",
    "  eEe  ",
    "   e   ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
)

# Roca del tick 380 al 388 (9 columnes)
PANELL_08 = (
    "         ",
    "         ",
    "         ",
    "         ",
    "         ",
    "         ",
    "         ",
    "         ",
    "         ",
    "         ",
    "         ",
    "         ",
    "         ",
    "         ",
    "         ",
    "    r    ",
    "   r%r   ",
    "  r%%%r  ",
    " r%%%%%r ",
    "r%%%%%%%r",
)

# Roca del tick 460 al 468 (9 columnes)
PANELL_10 = (
    "r%%%%%%%r",
    " r%%%%%r ",
    "  r%%%r  ",
    "   r%r   ",
    "    r    ",
    "         ",
    "         ",
    "         ",
    "         ",
    "         ",
    "         ",
    "         ",
    "         ",
    "         ",
    "         ",
    "         ",
    "         ",
    "         ",
    "         ",
    "         ",
)

# Roca del tick 560 al 571 (12 columnes)
PANELL_12 = (
    "r%%%%%r     ",
    " r%%%r      ",
    "  r%r       ",
    "   r        ",
    "            ",
    "            ",
    "            ",
    "            ",
    "            ",
    "            ",
    "            ",
    "            ",
    "            ",
    "            ",
    "            ",
    "            ",
    "        r   ",
    "       r%r  ",
    "      r%%%r ",
    "     r%%%%%r",
)

# Roca del tick 682 al 699 (18 columnes)
PANELL_14 = (
    "WqqqqqqqqqW       ",
    " WqqqqqqqW        ",
    "  WqqqqqW         ",
    "   WqqqW          ",
    "    WWW           ",
    "                  ",
    "                  ",
    "                  ",
    "                  ",
    "                  ",
    "                  ",
    "                  ",
    "                  ",
    "                  ",
    "                  ",
    "           WWW    ",
    "          WqqqW   ",
    "         WqqqqqW  ",
    "        WqqqqqqqW ",
    "       WqqqqqqqqqW",
)

# Roca del tick 820 al 834 (15 columnes)
PANELL_16 = (
    "#%%%%%%t%%%%%%#",
    " #%%%%%t%%%%%# ",
    "  #%%%%t%%%%#  ",
    "   #%%%t%%%#   ",
    "    #%%t%%#    ",
    "     ##@##     ",
    "               ",
    "               ",
    "               ",
    "               ",
    "               ",
    "               ",
    "               ",
    "               ",
    "     ##@##     ",
    "    #%%t%%#    ",
    "   #%%%t%%%#   ",
    "  #%%%%t%%%%#  ",
    " #%%%%%t%%%%%# ",
    "#%%%%%%t%%%%%%#",
)

# Roca del tick 940 al 944 (5 columnes)
PANELL_18 = (
    "     ",
    "     ",
    "     ",
    "     ",
    "     ",
    "     ",
    "     ",
    "     ",
    "     ",
    "     ",
    "     ",
    "     ",
    "     ",
    "     ",
    "     ",
    "     ",
    "     ",
    "  r  ",
    " r%r ",
    "r%%%r",
)

# Roca del tick 1020 al 1026 (7 columnes)
PANELL_20 = (
    "RyyyyyR",
    " RyyyR ",
    "  RyR  ",
    "   R   ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "   R   ",
    "  RyR  ",
    " RyyyR ",
    "RyyyyyR",
)

# Roca del tick 1120 al 1131 (12 columnes)
PANELL_22 = (
    "%%%%%%%%%%%%",
    "%%%%%%%%%%%%",
    "%%%%%%%%%%%%",
    "%%%%%%%%%%%%",
    "%%%%%%%%%%%%",
    "%%%%%%%%%%%%",
    "############",
    "            ",
    "            ",
    "            ",
    "            ",
    "            ",
    "            ",
    "            ",
    "            ",
    "            ",
    "            ",
    "            ",
    "            ",
    "            ",
)

# Roca del tick 1160 al 1171 (12 columnes)
PANELL_24 = (
    "            ",
    "            ",
    "            ",
    "            ",
    "            ",
    "            ",
    "            ",
    "            ",
    "            ",
    "            ",
    "            ",
    "            ",
    "            ",
    "############",
    "%%%%%%%%%%%%",
    "%%%%%%%%%%%%",
    "%%%%%%%%%%%%",
    "%%%%%%%%%%%%",
    "%%%%%%%%%%%%",
    "%%%%%%%%%%%%",
)

# Roca del tick 1240 al 1254 (15 columnes)
PANELL_26 = (
    "RyyyyyyyyyyyyyR",
    " RyyyyyyyyyyyR ",
    "  RyyyyyyyyyR  ",
    "   RyyyyyyyR   ",
    "    RyyyyyR    ",
    "     RRRRR     ",
    "               ",
    "               ",
    "               ",
    "               ",
    "               ",
    "               ",
    "               ",
    "               ",
    "     RRRRR     ",
    "    RyyyyyR    ",
    "   RyyyyyyyR   ",
    "  RyyyyyyyyyR  ",
    " RyyyyyyyyyyyR ",
    "RyyyyyyyyyyyyyR",
)

# Roca del tick 1340 al 1346 (7 columnes)
PANELL_28 = (
    "RyyyyyR",
    " RyyyR ",
    "  RyR  ",
    "   R   ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
)

# Roca del tick 1351 al 1361 (11 columnes)
PANELL_30 = (
    "    RyyyyyR",
    "     RyyyR ",
    "      RyR  ",
    "       R   ",
    "           ",
    "           ",
    "           ",
    "           ",
    "           ",
    "           ",
    "           ",
    "           ",
    "           ",
    "           ",
    "           ",
    "           ",
    "   R       ",
    "  RyR      ",
    " RyyyR     ",
    "RyyyyyR    ",
)

# Roca del tick 1440 al 1446 (7 columnes)
PANELL_32 = (
    "YwwwwwY",
    " YwwwY ",
    "  YwY  ",
    "   Y   ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
)

# Roca del tick 1452 al 1458 (7 columnes)
PANELL_34 = (
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "   Y   ",
    "  YwY  ",
    " YwwwY ",
    "YwwwwwY",
)

# Roca del tick 1464 al 1470 (7 columnes)
PANELL_36 = (
    "YwwwwwY",
    " YwwwY ",
    "  YwY  ",
    "   Y   ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
)

# Roca del tick 1476 al 1482 (7 columnes)
PANELL_38 = (
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "   Y   ",
    "  YwY  ",
    " YwwwY ",
    "YwwwwwY",
)

# Roca del tick 1488 al 1494 (7 columnes)
PANELL_40 = (
    "YwwwwwY",
    " YwwwY ",
    "  YwY  ",
    "   Y   ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
    "       ",
)

# Roca del tick 1560 al 1573 (14 columnes)
PANELL_42 = (
    "%%%%%%%%%%%%%%",
    "%%%%%%%%%%%%%%",
    "%%%%%%%%%%%%%%",
    "%%%%%%%%%%%%%%",
    "QQQQQQQQQQQQQQ",
    "              ",
    "              ",
    "              ",
    "              ",
    "              ",
    "              ",
    "              ",
    "              ",
    "              ",
    "              ",
    "QQQQQQQQQQQQQQ",
    "%%%%%%%%%%%%%%",
    "%%%%%%%%%%%%%%",
    "%%%%%%%%%%%%%%",
    "%%%%%%%%%%%%%%",
)

# Roca del tick 1680 al 1698 (19 columnes)
PANELL_44 = (
    "#%%%%%%%%t%%%%%%%%#",
    " #%%%%%%%t%%%%%%%# ",
    "  #%%%%%%t%%%%%%#  ",
    "   #%%%%%t%%%%%#   ",
    "    #%%%%t%%%%#    ",
    "     ####@####     ",
    "                   ",
    "                   ",
    "                   ",
    "                   ",
    "                   ",
    "                   ",
    "                   ",
    "                   ",
    "     ####@####     ",
    "    #%%%%t%%%%#    ",
    "   #%%%%%t%%%%%#   ",
    "  #%%%%%%t%%%%%%#  ",
    " #%%%%%%%t%%%%%%%# ",
    "#%%%%%%%%t%%%%%%%%#",
)

# Fons: estels, planeta llunya i muntanyes (es repeteix en bucle, 120 columnes)
FONS = (
    " *      .   *             .           *   .                    .            .  . .                                      ",
    "   .                                             . ...                . .           .     .                             ",
    "                        . *           .                                       .    .         *                          ",
    ".   .            .                      .            *           *.        .                                    .       ",
    "*          .                                                     .               .   ooooooo                .           ",
    "                                  .                                                 oOOOOOOOo                           ",
    "              *                    .                 *      .               .      ooOOOOOOOoo                          ",
    "            .           *                .                 *                        oOOOOOOOo      .         .          ",
    "           .          *                                  .                           ooooooo          .   .             ",
    "                                                  *                               *           .              .*         ",
    "  .                      .                               .. .           .                                               ",
    "                                                                                                       .                ",
    "                                                                                                                        ",
    "                                                                                                                        ",
    " ^^^^^^^       ^^^^^^^^^^^^     ^^^^^^^^^^^^    ^^^^^^^^^^         ^^^^^^^^^^    ^^^^^^^^^^^^     ^^^^^^^^^^^^       ^^^",
    "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   ^^^^^^",
    "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
    "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
    "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
    "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
)


LEVEL = {
    "name": 'NIVELL 1 - PRIMER CONTACTE',
    "duration": 1800,
    "paleta": PALETA,
    "art": junta(
        cel(120),
        PANELL_02,
        cel(75),
        PANELL_04,
        cel(75),
        PANELL_06,
        cel(93),
        PANELL_08,
        cel(71),
        PANELL_10,
        cel(91),
        PANELL_12,
        cel(110),
        PANELL_14,
        cel(120),
        PANELL_16,
        cel(105),
        PANELL_18,
        cel(75),
        PANELL_20,
        cel(93),
        PANELL_22,
        cel(28),
        PANELL_24,
        cel(68),
        PANELL_26,
        cel(85),
        PANELL_28,
        cel(4),
        PANELL_30,
        cel(78),
        PANELL_32,
        cel(5),
        PANELL_34,
        cel(5),
        PANELL_36,
        cel(5),
        PANELL_38,
        cel(5),
        PANELL_40,
        cel(65),
        PANELL_42,
        cel(106),
        PANELL_44,
    ),
    "paleta_fons": PALETA_FONS,
    "fons": FONS,
    "spawns": (
        # --- FASE 1 - BENVINGUDA (des del tick 0) ---
        (2, 0, 0.18, "recta"),
        (60, 0, 0.72, "ona"),
        (150, 0, 0.52, "recta"),
        (240, 1, 0.35, "zigzag"),
        (330, 0, 0.82, "picat"),
        (345, 2, 0.2, "ona"),
        (390, 0, 0.3, "zigzag"),
        # --- FASE 2 - PRIMERES ROQUES (des del tick 400) ---
        (420, 1, 0.6, "ona"),
        (440, 0, 0.15, "recta"),
        (475, 1, 0.42, "picat"),
        (505, 0, 0.78, "zigzag"),
        (535, 2, 0.45, "ona"),
        (600, 0, 0.25, "recta"),
        (600, 0, 0.75, "recta"),
        (630, 1, 0.5, "recta"),
        (655, 0, 0.3, "zigzag"),
        (655, 0, 0.7, "zigzag"),
        (655, 1, 0.5, "zigzag"),
        # --- FASE 3 - EL CANAL EN S (des del tick 700) ---
        (710, 2, 0.2, "ona"),
        (710, 2, 0.8, "ona"),
        (745, 0, 0.4, "picat"),
        (760, 0, 0.6, "picat"),
        (795, 0, 0.35, "recta"),
        (795, 1, 0.65, "recta"),
        (860, 2, 0.5, "zigzag"),
        (880, 0, 0.25, "ona"),
        (880, 1, 0.75, "ona"),
        (915, 0, 0.3, "picat"),
        (915, 1, 0.7, "picat"),
        (970, 2, 0.5, "recta"),
        # --- FASE 4 - LES PINCES (des del tick 1000) ---
        (1040, 0, 0.4, "zigzag"),
        (1040, 1, 0.6, "zigzag"),
        (1075, 0, 0.25, "ona"),
        (1075, 1, 0.75, "ona"),
        (1100, 2, 0.5, "recta"),
        (1145, 0, 0.55, "recta"),
        (1180, 0, 0.25, "recta"),
        (1205, 1, 0.6, "recta"),
        (1260, 2, 0.5, "ona"),
        (1285, 0, 0.35, "recta"),
        (1285, 1, 0.65, "recta"),
        (1310, 0, 0.4, "zigzag"),
        (1310, 1, 0.6, "zigzag"),
        (1375, 2, 0.5, "picat"),
        # --- FASE 5 - ESPRINT FINAL (des del tick 1400) ---
        (1408, 0, 0.25, "ona"),
        (1408, 1, 0.75, "ona"),
        (1450, 0, 0.5, "recta"),
        (1462, 1, 0.5, "recta"),
        (1520, 2, 0.5, "ona"),
        (1540, 0, 0.35, "zigzag"),
        (1540, 1, 0.65, "zigzag"),
        (1600, 0, 0.25, "ona"),
        (1600, 1, 0.75, "ona"),
        (1630, 2, 0.5, "picat"),
        (1660, 0, 0.4, "recta"),
        (1660, 1, 0.6, "recta"),
        (1730, 2, 0.5, "ona"),
        (1760, 0, 0.3, "recta"),
        (1760, 1, 0.7, "recta"),
    ),
}
